### ISSUE TITLE
Re styling

### ISSUE THREAD

**Issue by CHEWX** [getflywheel/local-addon-volumes#10]
Hi, 

Firstly, I can't quite believe this isn't in core.... 

Anyway, the styling has gone all skewed.

Attached.
![screen shot 2018-03-14 at 08 49 52](https://user-images.githubusercontent.com/5207147/37391978-db3f2734-2764-11e8-87d4-4705b366dd19.png)

Thanks.

**Comment by deviationist** [comment]
I second this, the styling in the table is broken. It kinda works tho, but does not look good.

**Comment by JiveDig** [comment]
Same here. Functional, but much more difficult to use.

**Comment by claygriffiths** [comment]
Closed with #11
