### ISSUE TITLE
Custom Mappings are lost after restart

### ISSUE THREAD

**Issue by halmos** [getflywheel/local-addon-volumes#12]
Any custom mapping I've added to the Volumes setting page are lost after quitting Local. The default mapping are retained, but I have to re-add the map settings each time i restart the Local app. Note that restarting the VM does not drop the settings. 

Also, possibly related - but after clicking 'Remap Volumes' the provisioning process hangs. If I run 'restart local machine' and restart the site everything seems to work as expected. 

Nothing notable / related is reported in Local's Log.

**Comment by halmos** [comment]
After debugging the plugin code, i think I've found the source of the error. https://github.com/getflywheel/local-addon-volumes/blob/fc3e0f0932069ef95b99e4de4df18330068a7c85/src/SiteInfoVolumes.jsx#L302-L306

In the `if` statement `typeof site.clonedImage != 'string'`, checking for non-strings is not a safe way to validate arrays. In my instance `typeof site.clonedImage == null`, with typeof  returning `'Object'` - because of this, the following line would attempt to `push` onto a `null` var. 

Instead, the `if` statement should look like `if (Array.isArray(site.clonedImage)) {`.

Changing this line fixed the issue for my situation.

**Comment by claygriffiths** [comment]
Thanks for the details! Feel free to submit a PR and I'll get it merged 😃

**Comment by afragen** [comment]
FWIW I have not seen this behavior. All of my mappings persist through a restart and/or machine reboot.

**Comment by claygriffiths** [comment]
@halmos,

This is addressed in 1.2.1. See https://github.com/getflywheel/local-addon-volumes/releases/tag/1.2.1

Thanks again for the heads up!
