### ISSUE TITLE
Is this compatible with Local 2.3.2 and custom environment v1.3.0?

### ISSUE THREAD

**Issue by pfurini** [getflywheel/local-addon-volumes#13]
I ask this because after upgrading a site using custom volume mappings, the mappings disappeared.
Then I re-added them, and Local started "Provisioning..." the changes.

The process stalled, and after 30 minutes or so I decided to try Restarting the virtual machine.. with no luck!
Now the entire virtual machine is corrupted, and I need to delete everything, and re-install Local and every site.

So it would be nice to have some support guarantee on this add-on (and others alike), otherwise I can't trust installing and using them anymore..

Thx
Paolo

**Comment by afragen** [comment]
It is not compatible at this time. I have already did this with Clay.

**Comment by pfurini** [comment]
Thanks @afragen to confirm this.. I hope to have some feedback from the author/flywheel team on when (whether?) they plan to fix this.
Or at least know what internals are changed, so that I can try fix it myself (I have fairly limited time, so I need at least some clue on where to put my hands on..)

Thx again
P.

**Comment by pfurini** [comment]
Please watch this thread on the Local Community forum, where I try to ask for some help fixing this:
http://local.getflywheel.com/community/t/local-volumes-add-on-stopped-working-in-2-3-2/7303
 
I really only need some minor guidance on what have changed in a breaking way on latest Local.

Thanks

**Comment by claygriffiths** [comment]
Hi @pfurini and @afragen,

Please try version 1.2.1. See https://github.com/getflywheel/local-addon-volumes/releases/tag/1.2.1

Sorry for the delay on this!

**Comment by afragen** [comment]
@claygriffiths I can confirm that this fixed the provisioning issue.

I tested with Local 2.3.1 and Local 2.3.2 and updated to environment 1.3.0 as well. Every combination worked.

Thanks!
