### ISSUE TITLE
When trying to remap a folder, the "provisioning" status freezes and nothing is changed

### ISSUE THREAD

**Issue by benjaminprojas** [getflywheel/local-addon-volumes#2]
I have set up some volume maps such as:

`my/local/folder` -> `/app/public/wp-content`

This works great, but when I try to remap it, it gets stuck on provisioning:

`my/local/folder2` -> `/app/public/wp-content`

This also happens when I try to delete the map and create it from scratch.

**Comment by mariadanieldeepak** [comment]
@benjaminprojas is right. I face this issue too. Could you help us provide a fix?

**Comment by aubreypwd** [comment]
I can confirm this....

![](https://cloudup.com/cqsD_PF0Nzb+?r.png)

This just stays this way.

**Comment by afragen** [comment]
This is happening again with v1.1.0

I had a _non-updated_ version of v1.1.0, it works again 🎆

**Comment by tazeverywhere** [comment]
Same here with v1.1.0, cannot remap or delete, stuck in "provisionning"

**Comment by afragen** [comment]
@tazeverywhere what do you see in the Volumes page? Can you show a screenshot?

**Comment by tazeverywhere** [comment]
Hi @afragen , this is the screenshot after clicking "remap volumes", "provisionning" for ever.
![local-ss](https://user-images.githubusercontent.com/4191041/27322516-bf6ae860-559e-11e7-840c-c5c70ac9b471.png)

**Comment by afragen** [comment]
I'm not sure this feature works when the folder is on another drive and not `/Users`

**Comment by tazeverywhere** [comment]
Thx for your help @afragen , I will try within `/Users` and give feedback, but unfortunately my DropBox is on a sd-card on my iMac :(

**Comment by afragen** [comment]
I wonder if you can point to a symlink as source? If not there's an app Sync Folders Pro in the App Store that can do a bidirectional folder to folder sync. Might be a kludge but should work.

**Comment by tazeverywhere** [comment]
@afragen , I did some test, the path with Alias in /Users seemed to work first (provisionning correctly), but visiting the site, Local say " Router error", and restart (site and virtualbox) didn't do the trick.

I re-did the test with my wp-content in a /Users subfolder and evrything works fine.
I think the Alias/external volume doasn't work for now.

Anyway, thx for the discussion & help !
