### ISSUE TITLE
Need to update package.json for Local v2.0

### ISSUE THREAD

**Issue by afragen** [getflywheel/local-addon-volumes#3]
The `package.json` file needs to be updated to install on Local by Flywheel 2.x

The change is on https://github.com/getflywheel/local-addon-volumes/blob/master/package.json#L30

`"local-by-flywheel": "^1.1.0"` to `"local-by-flywheel": ">1.1.0"`

**Comment by benjaminprojas** [comment]
I can verify this is an issue and resolved by making this one change.

**Comment by claygriffiths** [comment]
Fixed in 037fa76197a21ab69209d0303df068f19e894a0f
