### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by robinwittebol** [getflywheel/local-addon-volumes#5]

**Comment by randomstuart** [comment]
Having followed this process... http://local.getflywheel.com/community/t/moving-a-local-site-to-a-different-path/1923

On a PC I get stuck at number 6 when browsing for directory…

_“Sorry! You must provide a path in /Users”_

When I manually update path I get…

_“Sorry! There were invalid paths provided. Please ensure that all paths have a valid source and destination. Also, all source paths must begin with either /Users or /Volumes.”_

**Comment by claygriffiths** [comment]
Windows support is now available in [1.2.0](https://github.com/getflywheel/local-addon-volumes/releases/tag/1.2.0). See PR #9 for more info.

Thanks for the feedback!

**Comment by randomstuart** [comment]
Hi Clay, if this just merges the PR then it still won't work. The PR has issues that need to be fixed (see my comment above).

**Comment by claygriffiths** [comment]
@randomstuart Drives other than `C:\` aren't supported at the moment. We'll add support for that later.

If you use the `C:\` drive does it still not work?

**Comment by randomstuart** [comment]
Hi Clay, I'm not sure as I do not use the C drive for anything other than OS/Apps. I had to delete everything and start again to make it work with another drive

**Comment by lkhedlund** [comment]
> @randomstuart Drives other than `C:\` aren't supported at the moment. We'll add support for that later.
> 
> If you use the `C:\` drive does it still not work?

@claygriffiths I'm in C:\ and getting the same error.
