### ISSUE TITLE
How to use it for symlinking a plugin?

### ISSUE THREAD

**Issue by binarykitchen** [getflywheel/local-addon-volumes#7]
I have a plugin folder I want to symlink into the WP plugin folder local by flywheel is running on. Not sure what to enter in the HOST source and in the Container Destination?

For HOST source probably something like

`/Users/michael-heuberger/code/my-plugin`

but what to enter under Container Destination?? Maybe

a) `/Users/michael-heuberger/Local Sites/mylocalsite/app/public/wp-content/plugins` or
b) `/app/public/wp-content/plugins` ?

??

**Comment by afragen** [comment]
`/app/public/wp-content/plugins/my-plugin`

**Comment by binarykitchen** [comment]
woho, thanks for your superfast response
